spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_vue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
    user:
      name: user
      password: 123456
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    username: 2219084706@qq.com
    password: xczdeeknpsybdjgc
    port: 25

server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
