spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_vue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
    user:
      name: user
      password: 123456
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8